In [1]:
import spacy

In [2]:
nlp =spacy.load('en_core_web_md')

In [3]:
nlp(u'lion').vector

array([ 1.8963e-01, -4.0309e-01,  3.5350e-01, -4.7907e-01, -4.3311e-01,
        2.3857e-01,  2.6962e-01,  6.4332e-02,  3.0767e-01,  1.3712e+00,
       -3.7582e-01, -2.2713e-01, -3.5657e-01, -2.5355e-01,  1.7543e-02,
        3.3962e-01,  7.4723e-02,  5.1226e-01, -3.9759e-01,  5.1333e-03,
       -3.0929e-01,  4.8911e-02, -1.8610e-01, -4.1702e-01, -8.1639e-01,
       -1.6908e-01, -2.6246e-01, -1.5983e-02,  1.2479e-01, -3.7276e-02,
       -5.7125e-01, -1.6296e-01,  1.2376e-01, -5.5464e-02,  1.3244e-01,
        2.7519e-02,  1.2592e-01, -3.2722e-01, -4.9165e-01, -3.5559e-01,
       -3.0630e-01,  6.1185e-02, -1.6932e-01, -6.2405e-02,  6.5763e-01,
       -2.7925e-01, -3.0450e-03, -2.2400e-02, -2.8015e-01, -2.1975e-01,
       -4.3188e-01,  3.9864e-02, -2.2102e-01, -4.2693e-02,  5.2748e-02,
        2.8726e-01,  1.2315e-01, -2.8662e-02,  7.8294e-02,  4.6754e-01,
       -2.4589e-01, -1.1064e-01,  7.2250e-02, -9.4980e-02, -2.7548e-01,
       -5.4097e-01,  1.2823e-01, -8.2408e-02,  3.1035e-01, -6.33

In [4]:
doc = nlp(u'The quick brown fox jumped over the lazy dogs.')
doc.vector

array([-1.96635887e-01, -2.32740352e-03, -5.36607020e-02, -6.10564947e-02,
       -4.08843048e-02,  1.45266443e-01, -1.08268000e-01, -6.27789786e-03,
        1.48455709e-01,  1.90697408e+00, -2.57692993e-01, -1.95818534e-03,
       -1.16141019e-02, -1.62858292e-01, -1.62938282e-01,  1.18210977e-02,
        5.12646027e-02,  1.00078702e+00, -2.01447997e-02, -2.54611671e-01,
       -1.28316596e-01, -1.97198763e-02, -2.89733019e-02, -1.94347113e-01,
        1.26644447e-01, -8.69869068e-02, -2.20812604e-01, -1.58452198e-01,
        9.86308008e-02, -1.79210991e-01, -1.55290633e-01,  1.95643142e-01,
        2.66436003e-02, -1.64984968e-02,  1.18824698e-01, -1.17830629e-03,
        4.99809943e-02, -4.23077159e-02, -3.86111848e-02, -7.47400150e-03,
        1.23448208e-01,  9.60620027e-03, -3.32463719e-02, -1.77848607e-01,
        1.19390726e-01,  1.87545009e-02, -1.84173390e-01,  6.91781715e-02,
        1.28520593e-01,  1.48827005e-02, -1.78013414e-01,  1.10003807e-01,
       -3.35464999e-02, -

In [12]:
len(doc.vocab.vectors),len(nlp.vocab.vectors),len(doc.vocab),len(nlp.vocab)

(20000, 20000, 1344233, 1344233)

In [7]:
doc.vector.shape

(300,)

In [11]:
nlp(u'fox').vector.shape

(300,)

In [14]:
tokens = nlp(u'lion cat pet')

In [15]:
tokens = nlp(u'like love hate')

In [16]:
for token1 in tokens:
    for token2 in tokens:
        print(token1.text,token2.text,token1.similarity(token2))

like like 1.0
like love 0.65790397
like hate 0.6574652
love like 0.65790397
love love 1.0
love hate 0.6393099
hate like 0.6574652
hate love 0.6393099
hate hate 1.0


In [18]:
len(nlp.vocab.vectors)

20000

In [20]:
nlp.vocab.vectors.shape

(20000, 300)

In [29]:
tokens = nlp(u'dog cat hakak')

In [30]:
for token in tokens:
    print(token.text,token.has_vector,token.vector_norm,token.is_oov)

dog True 7.0336733 False
cat True 6.6808186 False
hakak False 0.0 True


In [31]:
 from scipy import spatial

In [53]:
cosine_similarity = lambda vec1,vec2: 1 - spatial.distance.cosine(vec1,vec2)

In [35]:
king = nlp.vocab['king'].vector
man = nlp.vocab['man'].vector
woman = nlp.vocab['woman'].vector

In [37]:
# king-man+woman -> queen,princess etc
new_vector = king-man+woman

In [38]:
computed_similarity = []
### for all words in my vocab
for word in nlp.vocab:
    if word.has_vector:
        if word.is_lower:
            if word.is_alpha:
                similarity = cosine_similarity(new_vector,word.vector)
                computed_similarity.append((word,similarity))

In [40]:
computed_similarity = sorted(computed_similarity,key=lambda item: - item[1])

In [43]:
print([t[0].text for t in computed_similarity[:10]])

['king', 'queen', 'commoner', 'highness', 'prince', 'sultan', 'maharajas', 'princes', 'kumbia', 'kings']


In [42]:
print([(t[0].text,t[1]) for t in computed_similarity[:10]])

[('king', 0.8024259805679321), ('queen', 0.7880843877792358), ('commoner', 0.6401076912879944), ('highness', 0.6401076912879944), ('prince', 0.6401076912879944), ('sultan', 0.6401076912879944), ('maharajas', 0.6208544373512268), ('princes', 0.6208544373512268), ('kumbia', 0.6208544373512268), ('kings', 0.6208544373512268)]


In [56]:
maria = nlp.vocab['maria'].vector
girl = nlp.vocab['girl'].vector
boy = nlp.vocab['boy'].vector
new_vector = maria-girl

In [63]:
computed_similarity = []
### for all words in my vocab
for word in nlp.vocab:
    if word.has_vector and word.is_lower and word.is_alpha:
        similarity = cosine_similarity(new_vector,word.vector)
        computed_similarity.append((word,similarity))

In [64]:
computed_similarity = sorted(computed_similarity,key=lambda item: - item[1])
print([t[0].text for t in computed_similarity[:10]])

['francesca', 'gabriela', 'barros', 'magdalena', 'pia', 'alejandra', 'belen', 'petra', 'giovanni', 'miyabi']


In [65]:
import nltk

In [66]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\U6077221\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


True

In [67]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [68]:
sid = SentimentIntensityAnalyzer()

In [69]:
a = 'this is a good movie'

In [70]:
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.508, 'pos': 0.492, 'compound': 0.4404}

In [72]:
a =  'This was the best, most awesome movie EVER MADE!!!'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.425, 'pos': 0.575, 'compound': 0.8877}

In [73]:
a = 'This was the worst film to ever disgrace the screen.'
sid.polarity_scores(a)

{'neg': 0.477, 'neu': 0.523, 'pos': 0.0, 'compound': -0.8074}

In [74]:
import pandas as pd

In [75]:
df = pd.read_csv('amazonreviews.tsv',sep='\t')

In [76]:
df.head()

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [77]:
df['label'].value_counts()

neg    5097
pos    4903
Name: label, dtype: int64

In [78]:
df.isnull().sum()

label     0
review    0
dtype: int64

In [79]:
df.dropna(inplace=True)

In [80]:
blanks=[]
for index,label,review in df.itertuples():
    if type(review)==str:
        if review.isspace():
            blanks.append(index)

In [82]:
len(blanks)
#df.drop(blanks,inplace=True,)

0

In [84]:
sid.polarity_scores(df.iloc[0]['review'])

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [88]:
df['scores'] = df['review'].apply(lambda review: sid.polarity_scoresrity_scores(review))

In [91]:
df['socres2']=df['review'].apply(sid.polarity_scores)

In [92]:
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  \
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...   
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...   
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...   
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...   
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...   

                                             socres2  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...

In [93]:
df['compound'] = df['scores'].apply(lambda d : d['compound'])

In [94]:
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  \
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...   
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...   
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...   
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...   
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...   

                                             socres2  compound  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...    0.9454  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...    0.8957  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...    0.9858  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...    0.9814  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...    0.9781

In [97]:
df.drop('socres2',axis=1,inplace=True)

In [98]:
df['comp_score']= df['compound'].map(lambda x :'pos' if x>=0 else 'neg')

In [99]:
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  compound comp_score  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...    0.9454        pos  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...    0.8957        pos  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...    0.9858        pos  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...    0.9814        pos  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...    0.9781        pos

In [100]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [101]:
accuracy_score(df['label'],df['comp_score'])

0.7091

In [102]:
confusion_matrix(df['label'],df['comp_score'])

array([[2623, 2474],
       [ 435, 4468]], dtype=int64)

In [104]:
print(classification_report(df['label'],df['comp_score']))

              precision    recall  f1-score   support

         neg       0.86      0.51      0.64      5097
         pos       0.64      0.91      0.75      4903

   micro avg       0.71      0.71      0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000



### code along

In [105]:
import numpy as np
import pandas as pd

In [111]:
df2 = pd.read_csv('moviereviews.tsv',sep='\t')
df2.head()

label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

In [112]:
df2.isnull().sum()

label      0
review    35
dtype: int64

In [113]:
df2.dropna(inplace=True)

In [117]:
blanks=[]
for index,label,review in df2.itertuples():
    if type(review)==str:
        if review.isspace():
            blanks.append(index)
len(blanks)

0

In [116]:
df2.drop(blanks,inplace=True,axis=0)

In [119]:
df2['label'].value_counts()

pos    969
neg    969
Name: label, dtype: int64

In [121]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [122]:
sid = SentimentIntensityAnalyzer()

In [123]:
df['scores'] = df['review'].map(sid.polarity_scores)

In [124]:
df.head()

label                                             review  \
0   pos  I loved this movie and will watch it again. Or...   
1   pos  A warm, touching movie that has a fantasy-like...   
2   pos  I was not expecting the powerful filmmaking ex...   
3   neg  This so-called "documentary" tries to tell tha...   
4   pos  This show has been my escape from reality for ...   

                                              scores  
0  {'neg': 0.062, 'neu': 0.695, 'pos': 0.243, 'co...  
1  {'neg': 0.033, 'neu': 0.783, 'pos': 0.184, 'co...  
2  {'neg': 0.097, 'neu': 0.795, 'pos': 0.108, 'co...  
3  {'neg': 0.116, 'neu': 0.832, 'pos': 0.052, 'co...  
4  {'neg': 0.031, 'neu': 0.796, 'pos': 0.173, 'co...

In [125]:
df['compound'] = df['scores'].map(lambda d: d['compound'])

In [126]:
df.head()

label                                             review  \
0   pos  I loved this movie and will watch it again. Or...   
1   pos  A warm, touching movie that has a fantasy-like...   
2   pos  I was not expecting the powerful filmmaking ex...   
3   neg  This so-called "documentary" tries to tell tha...   
4   pos  This show has been my escape from reality for ...   

                                              scores  compound  
0  {'neg': 0.062, 'neu': 0.695, 'pos': 0.243, 'co...    0.8720  
1  {'neg': 0.033, 'neu': 0.783, 'pos': 0.184, 'co...    0.9549  
2  {'neg': 0.097, 'neu': 0.795, 'pos': 0.108, 'co...    0.7201  
3  {'neg': 0.116, 'neu': 0.832, 'pos': 0.052, 'co...   -0.9821  
4  {'neg': 0.031, 'neu': 0.796, 'pos': 0.173, 'co...    0.9874

In [127]:
df['comp_score'] = df['compound'].map(lambda x: 'pos' if x>=0 else 'neg')

In [128]:
df.head()

label                                             review  \
0   pos  I loved this movie and will watch it again. Or...   
1   pos  A warm, touching movie that has a fantasy-like...   
2   pos  I was not expecting the powerful filmmaking ex...   
3   neg  This so-called "documentary" tries to tell tha...   
4   pos  This show has been my escape from reality for ...   

                                              scores  compound comp_score  
0  {'neg': 0.062, 'neu': 0.695, 'pos': 0.243, 'co...    0.8720        pos  
1  {'neg': 0.033, 'neu': 0.783, 'pos': 0.184, 'co...    0.9549        pos  
2  {'neg': 0.097, 'neu': 0.795, 'pos': 0.108, 'co...    0.7201        pos  
3  {'neg': 0.116, 'neu': 0.832, 'pos': 0.052, 'co...   -0.9821        neg  
4  {'neg': 0.031, 'neu': 0.796, 'pos': 0.173, 'co...    0.9874        pos

In [129]:
accuracy_score(df['label'],df['comp_score'])

0.7317318998824123

In [130]:
confusion_matrix(df['label'],df['comp_score'])

array([[1729, 1250],
       [ 347, 2627]], dtype=int64)

In [131]:
print(classification_report(df['label'],df['comp_score']))

              precision    recall  f1-score   support

         neg       0.83      0.58      0.68      2979
         pos       0.68      0.88      0.77      2974

   micro avg       0.73      0.73      0.73      5953
   macro avg       0.76      0.73      0.73      5953
weighted avg       0.76      0.73      0.73      5953

