In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv('npr.csv')

In [3]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [4]:
npr.shape

(11992, 1)

In [8]:
npr['Article'][0]
len(npr.loc[0,'Article'])

7646

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
cv = CountVectorizer(max_df=0.9,min_df=2,stop_words='english')

In [12]:
dtm=cv.fit_transform(npr['Article'])

In [13]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [14]:
from sklearn.decomposition import LatentDirichletAllocation

In [15]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [16]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='batch', learning_offset=10.0,
             max_doc_update_iter=100, max_iter=10, mean_change_tol=0.001,
             n_components=7, n_jobs=None, n_topics=None, perp_tol=0.1,
             random_state=42, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [17]:
# Grab the vocabulary

len(cv.get_feature_names()) 

54777

In [21]:
cv.get_feature_names()[41000]

'reproductive'

In [22]:
import random

random_word_id = random.randint(0,54777)
cv.get_feature_names()[random_word_id]

'heats'

In [23]:
# Grab the topics

In [25]:
len(LDA.components_)

7

In [26]:
type(LDA.components_)

numpy.ndarray

In [28]:
LDA.components_.shape # probability of each words

(7, 54777)

In [29]:
# highest probability words per topic


In [30]:
single_topic = LDA.components_[0]

In [82]:
single_topic

array([8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
       1.43006821e-01, 1.42902042e-01, 1.42861626e-01])

In [31]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [32]:
import numpy as np

In [36]:
arr = np.array([10,200,1])
arr

array([ 10, 200,   1])

In [37]:
np.sort(arr)

array([  1,  10, 200])

In [39]:
np.argsort(arr)

array([2, 0, 1], dtype=int64)

In [43]:
single_topic.argsort() # sorts in lowest to highest and returns indices

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [84]:
single_topic[2475],single_topic[42993]

(0.1428571430851871, 6247.245510521016)

In [85]:
single_topic.argsort()[-10:] # last 10 values

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [48]:
top_ten_words = single_topic.argsort()[-10:]

In [49]:
for index in top_ten_words:
    print(cv.get_feature_names()[index])

new
percent
government
company
million
care
people
health
said
says


In [50]:
top_20_words = single_topic.argsort()[-20:]
for index in top_20_words:
    print(cv.get_feature_names()[index])

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [54]:
# for all topics

for i,topic in enumerate(LDA.components_):
    print(f"top 15 words for topic number {i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n\n')

top 15 words for topic number 0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']



top 15 words for topic number 1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']



top 15 words for topic number 2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']



top 15 words for topic number 3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']



top 15 words for topic number 4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']



top 15 words for topic number 5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time',

In [55]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [57]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [59]:
topic_results=LDA.transform(dtm)

In [61]:
topic_results.shape

(11992, 7)

In [66]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [67]:
npr.loc[0,'Article']

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [76]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 0], dtype=int64)

In [77]:
npr['Topic'] = topic_results.argmax(axis=1)

In [78]:
npr.head()

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      1
4  From photography, illustration and video, to d...      2

In [81]:
npr['Topic'].value_counts(sort=False)

0    1313
1    2004
2    1838
3    1485
4    1943
5    2458
6     951
Name: Topic, dtype: int64

### Non negative Matrix Factorization

In [87]:
npr = pd.read_csv('npr.csv')`

In [91]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [88]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [89]:
tfidf = TfidfVectorizer(max_df=0.95,min_df=2,stop_words='english')

In [92]:
dtm = tfidf.fit_transform(npr['Article'])

In [93]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.float64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [94]:
from sklearn.decomposition import NMF

In [95]:
nmf_model = NMF(n_components=7,random_state=0)

In [97]:
nmf_model.fit(dtm)

NMF(alpha=0.0, beta_loss='frobenius', init=None, l1_ratio=0.0, max_iter=200,
  n_components=7, random_state=0, shuffle=False, solver='cd', tol=0.0001,
  verbose=0)

In [99]:
tfidf.get_feature_names()[2300]

'albala'

In [100]:
nmf_model.components_.shape

(7, 54777)

In [101]:
nmf_model.components_[0]

array([0.00000000e+00, 2.50029599e-01, 0.00000000e+00, ...,
       1.70366808e-03, 2.37617344e-04, 0.00000000e+00])

In [103]:
for index,topic in enumerate(nmf_model.components_):
    print(f'TOP 15 words for topic #{index}')
    print([tfidf.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n\n')

TOP 15 words for topic #0
['new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']



TOP 15 words for topic #1
['gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']



TOP 15 words for topic #2
['senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']



TOP 15 words for topic #3
['officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']



TOP 15 words for topic #4
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']



TOP 15 words for topic #5
['love', 've', 'don', 'album', 'way', 'time'

In [104]:
topic_results = nmf_model.transform(dtm)

In [106]:
topic_results.shape

(11992, 7)

In [109]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 0, 4, 3], dtype=int64)

In [110]:
npr['topic'] = topic_results.argmax(axis=1)

In [111]:
npr.head()

Article  topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      3
4  From photography, illustration and video, to d...      6

#{1:'politics',2:}
apply map with dict to replace the numbers